someengineering/fixfrontend

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/workspace-settings-billing/ChangePaymentMethod.tsx
- src/pages/panel/workspace-settings-billing/utils/securityTierToDescription.ts
- src/pages/panel/workspace-settings-billing/utils/securityTierToLabel.ts
- src/shared/types/server/shared/Payment.ts
> New pricing model

- src/containers/auth/AuthContainer.tsx
- src/containers/panel/PanelContainer.tsx
> Show beta logo only on login

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
> [refactor] prune i18n messages

- src/shared/error-boundary-fallback/ErrorBoundaryFallback.tsx
fix error boundary UI modal in small screens
from:
to:
> [fix] fix error boundary UI modal

- src/shared/layouts/panel-layout/UserProfileButton.tsx
redirect to / after change workspace in user profile button
> [fix] redirect to / after change workspace

- src/core/events/WebSocketEvents.tsx
- src/pages/panel/inventory/DownloadCSVButton.tsx
- src/shared/charts/PieChart.tsx
remove backdrop from piechart popover,
From:
To:
> [fix] pie chart popover

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/accounts/AccountRow.tsx
- src/pages/panel/accounts/AccountsTable.tsx
- src/pages/panel/accounts/AccountsTableItem.tsx
- src/pages/panel/accounts/patchAccountScanDisable.mutation.ts
- src/pages/panel/accounts/patchAccountScanEnable.mutation.ts
- src/shared/constants/endPoints.ts
- src/shared/types/server/responses/shared/Account.ts
add security scan checkbox in accounts rows
> [feat] add security scan checkbox in accounts rows

- src/pages/panel/user-settings/UserSettingsFormPassword.tsx
not logout after password change
> [fix] not logout after password change

- .github/workflows/publish.yml
- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/inventory/utils/ResourceDetailChangeLogHistory.tsx
[remove haveDiff](https://github.com/someengineering/fixfrontend/commit/79ff23c24370e944a65cac48c51691afa0ccf897)
> [Hotfix] resource detail change log history

- src/shared/charts/PieChart.tsx
add min angle of 25d to the piechart
> [fix] add min angle of 25d to the piechart

- package.json
- src/shared/fixquery-parser/parser.test.ts
- src/shared/fixquery-parser/parser.ts
- src/shared/fixquery-parser/query.test.ts
- src/shared/fixquery-parser/query.ts
- yarn.lock
> [feat] Query access and update functionality 

- index.html
- src/core/theme/Theme.tsx
> [fix] add nonce into emotion cache

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/inventory/ResourceDetail.tsx
- src/pages/panel/shared/failed-checks/FailedChecks.tsx
- src/shared/types/server/responses/shared/NodeSecurity.ts
Show benchmarks in resource detail
> [feat] show benchmarks in failedChecks

- src/pages/panel/security/TopFiveChecksCard.tsx
- src/shared/types/server/responses/shared/FailedCheck.ts
Add benchmarks to top five security checks
> [fix] add benchmarks to top five security checks

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/workspace-settings-billing/ChangePaymentMethod.tsx
- src/pages/panel/workspace-settings-billing/WorkspaceSettingsBillingPage.tsx
handle trial product tier correctly
> fix(billing): handle trial product tier correctly

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/inventory/ResourceDetail.tsx
- src/pages/panel/security/Overview.tsx
- src/pages/panel/shared/failed-checks/FailedChecks.tsx
- src/pages/panel/shared/utils/HeatmapCard.tsx
- src/pages/panel/shared/utils/PieCard.tsx
- src/pages/panel/shared/utils/PieResourceCheckScore.tsx
- src/pages/panel/shared/utils/chartToShow.tsx
- src/pages/panel/shared/utils/createPieDataFromNonCompliance.ts
- src/shared/charts/Heatmap.none
- src/shared/charts/Heatmap.tsx
- src/shared/charts/PieChart.tsx
add heatmap to the security-page
> [feat] add heatmap to the security-page

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/inventory/InventoryPage.tsx
- src/pages/panel/inventory/InventoryTemplateBoxes.tsx
add template searches when search is empty or all
> WIP: [feat] add template searches when search is empty or all

- src/pages/panel/inventory/InventoryTemplateBoxes.tsx
> Update search to look at last 7d

- src/pages/panel/inventory/InventoryTemplateBoxes.tsx
fix cursor in inventory template boxes
> [fix]: fix cursor in inventory template boxes

- src/pages/panel/inventory/InventoryPage.tsx
Reset state on remove search in inventory page
> [fix] Reset state on remove search in inventory page

- src/core/auth/AuthGuard.tsx
- src/pages/auth/login/LoginPage.tsx
- src/pages/panel/workspace-settings-billing/WorkspaceSettingsBillingPage.tsx
- src/shared/types/server/responses/GetWorkspaces.ts
fix trial number in billing page
> [fix] fix trial number in billing page

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
> [fix] Missing strings

- src/pages/panel/inventory/InventoryTemplateBoxes.tsx
> Update orphaned snapshots search

- src/pages/panel/inventory/InventoryTemplateBoxes.tsx
> Update public bucket detection rule

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/accounts/AccountsTableItem.tsx
- src/pages/panel/inventory/InventoryTable.tsx
- src/pages/panel/workspace-settings-billing/WorkspaceSettingsBillingTable.tsx
- src/pages/panel/workspace-settings-users/WorkspaceSettingsUserInvitationsTable.tsx
- src/pages/panel/workspace-settings-users/WorkspaceSettingsUsersTable.tsx
- src/shared/constants/StorageKeys.ts
- src/shared/constants/index.ts
- src/shared/utils/localstorage.ts
- src/shared/utils/usePersistState.ts
add persist state to the project
> feat(persist-state): add persist state to the project

- src/pages/panel/inventory/InventoryTemplateBoxes.tsx
> Update public bucket detection

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/workspace-settings-users/WorkspaceSettingsUserRoles.tsx
- src/pages/panel/workspace-settings-users/WorkspaceSettingsUserRow.tsx
- src/pages/panel/workspace-settings-users/putWorkspaceRoles.mutation.ts
- src/pages/panel/workspace-settings-users/workspaceSettingsUserRoleToString.ts
- src/shared/constants/endPoints.ts
- src/shared/types/server/requests/PutWorkspaceRoles.ts
- src/shared/types/server/requests/index.ts
- src/shared/types/server/responses/GetWorkspaceUsers.ts
- src/shared/types/server/responses/index.ts
- src/shared/types/server/responses/shared/UserRole.ts
- src/shared/types/server/responses/shared/index.ts
add edit roles in workspace user page
> [feat] add edit roles in workspace user page

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/workspace-settings-billing/ChangePaymentMethod.tsx
- src/pages/panel/workspace-settings-billing/utils/productTierToDescription.ts
> [fix] fix prices

- package.json
- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/security/Overview.tsx
- src/pages/panel/security/VulnerableResourcesTimeline.tsx
- src/shared/charts/Heatmap.tsx
- src/shared/event-button/EventButton.tsx
- src/shared/types/server/responses/GetWorkspaceInventoryReportSummary.ts
- src/shared/types/server/responses/index.ts
- yarn.lock
add failing check timeline to security overview
> [feat] add failing check timeline to security overview

- src/pages/panel/inventory/InventoryTemplateBoxes.tsx
include account settings in public bucket check
> feat(search): include account settings in public bucket check

- src/shared/fixquery-parser/lexer.ts
- src/shared/fixquery-parser/parser.test.ts
- src/shared/fixquery-parser/parser.ts
- src/shared/fixquery-parser/query.ts
- src/shared/utils/optional.ts
> [feat] Add aggregate parser

- src/pages/panel/security/VulnerableResourcesTimeline.tsx
- src/shared/providers/InnerI18nProvider.tsx
- src/shared/providers/i18n.ts
localize dayjs and fixed dayjs implementation on VulnerableResourcesTimeline
> [fix] localize dayjs

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/setup-cloud/SetupCloudPage.tsx
> [fix] fix video posters in setup-cloud-page

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/workspace-settings-billing/WorkspaceSettingsBillingPage.tsx
fix cycle price in workspace settings billing page
> [fix] fix cycle price in workspace settings billing page

- src/pages/panel/inventory/InventoryTemplateBoxes.tsx
> deleteme -> delete

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/security/OverallScore.tsx
- src/pages/panel/shared/utils/createPieDataFromNonCompliance.ts
> Fix translation and sentence.

- src/pages/panel/inventory/InventoryTemplateBoxes.tsx
> Re-order the example searches

- src/shared/fixquery-parser/parser.ts
- src/shared/fixquery-parser/query.test.ts
> [fix] keywords are allowed as json string

- src/shared/fixquery-parser/parser.test.ts
- src/shared/fixquery-parser/parser.ts
- src/shared/fixquery-parser/query.ts
> [fix] sort order is lowercase

- src/shared/fixquery-parser/query.test.ts
- src/shared/fixquery-parser/query.ts
> [feat] Allow combining terms

- src/shared/fix-query-parser/query.ts
> [fix] MergeQuery term part

- src/shared/fix-query-parser/parser.test.ts
- src/shared/fix-query-parser/parser.ts
- src/shared/fix-query-parser/query.test.ts
- src/shared/fix-query-parser/query.ts
> [fix] Delete properties correctly and handle navigation

- src/shared/fix-query-parser/parser.test.ts
- src/shared/fix-query-parser/parser.ts
- src/shared/fix-query-parser/query.ts
> Fix MergeQuery Parser

- src/shared/fix-query-parser/parser.test.ts
- src/shared/fix-query-parser/parser.ts
> fix parsing path with keywords

- src/containers/panel/PanelRoutes.tsx
- src/pages/auth/login/LoginPage.tsx
- src/pages/panel/inventory/InventoryTemplateBoxes.tsx
- src/pages/panel/inventory/resource-detail/utils/nodeChange.tsx
- src/shared/event-button/EventButton.tsx
fix critical bug with compliant diff not exists
> [hotfix] fix critical bug with compliant diff not exists

- src/shared/fix-query-parser/FixQueryContext.tsx
- src/shared/fix-query-parser/query.test.ts
- src/shared/fix-query-parser/query.ts
> feat: show if the query can be displayed with form fields only

- src/pages/panel/inventory/InventoryAdvanceSearch.tsx
- src/pages/panel/inventory/InventoryPage.tsx
- src/pages/panel/inventory/resource-detail/utils/ResourceDetailChangeLogSelectedHistoryDiff.tsx
- src/shared/fix-query-parser/FixQueryContext.tsx
- src/shared/types/server/responses/GetWorkspaceInventoryNodeHistory.ts
reset error in inventory when there's no query
> [Fix] reset error in inventory when there's no query

- src/shared/event-button/EventButton.tsx
- src/shared/types/server/web-socket-event/WebSocketEvent.ts
add account collected event to events
> [feat] add account collected event to events

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/inventory/inventory-form/InventoryFormFilterRowStringValue.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormFilterRowValues.tsx
Change null to undefined
No. 626
> [fix] change null to undefined

- .github/workflows/pr-checks.yml
> [feat] add test build into every pr

- .github/workflows/pr-checks.yml
> [fix] add env in pr check yaml

- src/pages/panel/inventory/inventory-form/InventoryForm.tsx
fix inventory filters: do not filter clouds when only cloud is selected
No. 626
> [fix] do not filter clouds when only cloud is selected

- .github/workflows/publich-pr.yml
Separate pr checks and publish logic
> [fix] Separate pr checks and publish logic

- src/pages/panel/inventory/inventory-form/InventoryForm.tsx
remove duplicates from account and region and kind
> [fix]: remove duplicates from account and region and kind

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/inventory/inventory-form/InventoryFormDefaultValue.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormMoreValue.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormSeverity.tsx
####Issue No: 631
When pressing esc in a property search box
> [fix] when pressing esc in a property search box

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/accounts/AccountRow.tsx
next scan should display date when not at the same day
> [fix] next scan should display date when not at the same day

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/inventory/InventoryAdvanceSearch.tsx
- src/pages/panel/inventory/inventory-form/InventoryForm.tsx
####Issue No: 632
Add an alert that something extra is in the query than forms
> [fix] Add an alert that something extra is in the query than forms

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/inventory/DownloadCSVButton.tsx
- src/pages/panel/inventory/InventoryPage.tsx
- src/pages/panel/inventory/InventoryTable.tsx
- src/pages/panel/shared/queries/postWorkspaceInventorySearchTableDownload.mutation.ts
- src/shared/types/server/requests/PostWorkspaceInventorySearchTable.ts
- src/shared/types/server/requests/index.ts
####Issue No: 660
fix CSV Download post params
> [fix] CSV Download delivers wrong entries

- src/pages/panel/inventory/InventoryAdvanceSearch.tsx
- src/pages/panel/inventory/InventoryPage.tsx
- src/pages/panel/inventory/inventory-form/InventoryForm.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormAccount.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormCloud.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormCloudValues.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormFullTextSearch.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormFullTextSearchValue.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormKind.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormMore.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormMoreValue.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormRegion.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormRegionValues.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormReset.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormRest.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormSeverity.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormTagsValue.tsx
- src/shared/fix-query-parser/FixQueryContext.tsx
Search is not cleaned when clicking on the inventory tab
> [fix] search is not cleaned when clicking on the inventory tab

- src/containers/panel/PanelRoutes.tsx
- src/core/auth/AuthGuard.tsx
- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/auth/login/LoginPage.tsx
- src/pages/auth/register/RegisterPage.tsx
- src/pages/auth/verify-email/VerifyEmailPage.tsx
- src/pages/panel/inventory/InventoryTemplateBoxes.tsx
- src/pages/subscription/choose-workspace/ChooseWorkspacePage.tsx
- src/shared/constants/panelUI.ts
- src/shared/error-boundary-fallback/ErrorBoundaryFallback.tsx
- src/shared/fix-query-parser/FixQueryContext.tsx
- src/shared/layouts/panel-layout/PanelAppBar.tsx
- src/shared/layouts/panel-layout/PanelDrawer.tsx
- src/shared/layouts/panel-layout/UserProfileButton.tsx
- src/shared/login-social-media/LoginSocialMedia.tsx
fix everything regarding to wrong navigation (fix homepage)
> [fix] fix everything regarding to wrong navigation (fix homepage)

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/inventory/InventoryAdvanceSearch.tsx
- src/pages/panel/inventory/InventoryAdvanceSearchTextField.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormField.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormFilterRowOpType.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormFilterRowStringValue.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormFullTextSearchValue.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormMore.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormMoreValue.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormReset.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormTagsValue.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormValue.tsx
- src/shared/fix-query-parser/FixQueryContext.tsx
- src/shared/react-window/ListboxComponent.tsx
- [fix(inventory-form-field): remove shadow from fields](https://github.com/someengineering/fixfrontend/commit/d517a3f79c89f4458a68bad98ce2b2c4c31a44d1)
- [fix(inventory-advance-search-field): fix changing advance search won't apply](https://github.com/someengineering/fixfrontend/commit/8cc96cf72e63bcf94c454ef322091e90fdf2e4e4) 
- [fix(inventory-form-filter-row-op-type): better handling OP](https://github.com/someengineering/fixfrontend/commit/400acd994061e4b3da29af0f3ad91141824a1fd3)
- [fix(inventory-form): enhance more and reset button UI](https://github.com/someengineering/fixfrontend/commit/29efe3cacafc73cd1de57e103b83a6eb5bfcd5f8)
- [fix(inventory-form-row-string-value): make it autofocus and fix always open popover](https://github.com/someengineering/fixfrontend/commit/05801776a63bbf …
> [fix] inventory field ui update

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/setup-cloud/SetupCloudPage.tsx
- src/shared/event-button/EventButton.tsx
- src/shared/event-button/EventItem.stories.tsx
- src/shared/event-button/EventItem.tsx
- src/shared/types/server/web-socket-event/WebSocketEvent.ts
- src/shared/types/server/web-socket-event/index.ts
> [fix] add cloud events

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/inventory/DownloadCSVButton.tsx
- src/pages/panel/inventory/InventoryAdvanceSearch.tsx
- src/pages/panel/inventory/InventoryTable.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormMore.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormReset.tsx
- src/pages/panel/security/AccountCard.tsx
- src/pages/panel/shared/failed-checks/FailedChecks.tsx
- src/pages/panel/workspace-settings-accounts/WorkspaceSettingsAccountRow.tsx
- src/pages/panel/workspace-settings-users/WorkspaceSettingsUserInvitationRow.tsx
- src/pages/panel/workspace-settings-users/WorkspaceSettingsUserRoles.tsx
- src/pages/panel/workspace-settings-users/WorkspaceSettingsUserRow.tsx
- src/pages/panel/workspace-settings/WorkspaceSettingsFormItem.tsx
- src/pages/panel/workspace-settings/workspace-alerting-settings/WorkspaceAlertingSettings.tsx
- src/shared/charts/Heatmap.tsx
- src/shared/disabled-with-permission/DisabledWithPermission.tsx
- src/shared/language-button/LanguageButton.tsx
- src/shared/layouts/panel-layout/DrawerMenu.tsx
- src/shared/layouts/panel-layout/UserProfileButton.tsx
fix tooltip placement issues and add some arrows
> [fix] fix tooltip placement issues and add some arrows

- src/pages/panel/workspace-settings/WorkspaceSettingsFormItem.tsx
- src/pages/panel/workspace-settings/workspace-alerting-settings/WorkspaceAlertingSettings.tsx
remove disabled buttons
From:
To:
> [fix] remove disabled buttons

- src/pages/panel/workspace-settings-billing/utils/paymentMethods.ts
> [fix]: bring back aws market support

- .eslintrc.cjs
- .prettierignore
- index.html
- package.json
- vite.config.ts
- yarn.lock
> [hotfix] fix trackjs installer script

- package.json
- src/pages/panel/inventory/inventory-form/InventoryFormFilterRowProperty.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormValue.tsx
- src/pages/panel/inventory/inventory-form/utils/postCostumedWorkspaceInventoryPropertyAttributes.query.ts
- src/pages/panel/shared/queries/postWorkspaceInventoryPropertyPathComplete.query.ts
- src/pages/panel/shared/queries/postWorkspaceInventoryPropertyPathCompleteFqn.query.ts
- src/pages/panel/workspace-settings-accounts-setup-cloud-gcp/WorkspaceSettingsAccountsSetupCloudGCPUploadKey.tsx
- src/pages/panel/workspace-settings-accounts-setup-cloud-gcp/getWorkspaceCloudAccountGCPKey.query.ts
fix the implmenetation of gcp key get api
> [hotfix] fix the implmenetation of gcp key get api

- index.html
- src/core/auth/AuthGuard.tsx
- src/core/auth/WorkspaceGuard.tsx
- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/shared/absolute-navigate/AbsoluteNavigateInnerProvider.tsx
- src/shared/absolute-navigate/AbsoluteNavigateProvider.tsx
- src/shared/error-boundary-fallback/ErrorBoundaryFallback.tsx
- src/shared/error-boundary-fallback/ErrorModal.tsx
- src/shared/error-boundary-fallback/index.ts
- src/shared/loading/LoadingSuspenseFallback.tsx
- src/shared/loading/Spinner.tsx
- src/shared/utils/localstorage.ts
take the workspace id from URL always
> [fix] take the workspace id from URL always

- src/core/auth/AuthGuard.tsx
- src/core/auth/WorkspaceGuard.tsx
- src/shared/utils/localstorage.ts
fix the icon, button and title text in the workspace guard
> [fix] the icon, button and title text in the workspace guard

- .github/workflows/pr-checks.yml
- .github/workflows/publish-pr.yml
- .github/workflows/publish.yml
- src/core/auth/WorkspaceGuard.tsx
- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/shared/layouts/panel-layout/UserProfileButton.tsx
update workspace guard messages
> [hotfix] update workspace guard messages

- index.html
fix badly implemented trackjs token in installation
> [fix] fix badly implemented trackjs token in installation

- index.html
Check if TrackJS is on dev and add dev application
> [fix] check if TrackJS is on dev and add dev application

- index.html
fix isLocalhost if clause in trackjs install process
> [hotfix] fix isLocalhost if clause in trackjs install process

- package.json
- src/Main.tsx
- src/assets/icons/createIcon.tsx
- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/benchmark-detail/BenchmarkDetailPage.tsx
- src/pages/panel/benchmark-detail/BenchmarkDetailSplitter.tsx
- src/pages/panel/inventory/inventory-form/utils/getAutoCompleteFromKey.test.ts
- src/pages/panel/security/VulnerableResourcesTimeline.tsx
- src/shared/splitter/Gutter.tsx
- src/shared/splitter/Splitter.tsx
- src/shared/splitter/enums.ts
- src/shared/splitter/index.css
- src/shared/splitter/index.ts
- src/shared/splitter/isTouchDevice.ts
- src/shared/splitter/state/index.ts
- src/shared/splitter/state/pair.ts
- src/shared/splitter/state/reducer.actions.ts
- src/shared/splitter/state/reducer.ts
- src/shared/splitter/useEventListener.ts
- src/shared/splitter/utils/flattenChildren.ts
- src/shared/splitter/utils/getGutterSize.ts
- src/shared/splitter/utils/getInnerSize.ts
- src/shared/splitter/utils/index.ts
- src/shared/splitter/utils/isTouchEvent.ts
- yarn.lock
> [hotfix]: fix nonce in splitter

- src/assets/icons/aws-logo.svg
- src/assets/icons/azure-logo.svg
- src/assets/icons/createIcon.tsx
- src/assets/icons/index.ts
- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/benchmark-detail/BenchmarkCheckCollectionDetail.tsx
- src/pages/panel/benchmark-detail/BenchmarkDetailCheckDetail.tsx
- src/pages/panel/benchmark-detail/BenchmarkDetailSplitter.tsx
- src/pages/panel/benchmark-detail/BenchmarkDetailView.tsx
- src/pages/panel/inventory/InventoryTable.tsx
- src/pages/panel/shared/failed-checks/FailedCheckIgnoreButton.tsx
- src/pages/panel/workspace-settings-accounts-setup-cloud-gcp/WorkspaceSettingsAccountsSetupCloudGCPInstructions.tsx
- src/pages/panel/workspace-settings-accounts-setup-cloud/WorkspaceSettingsAccountsSetupCloudPage.tsx
- src/pages/panel/workspace-settings-accounts/WorkspaceSettingsAccountsTableItem.tsx
- src/pages/panel/workspace-settings-billing/WorkspaceSettingsBillingTable.tsx
- src/pages/panel/workspace-settings-users/WorkspaceSettingsUserInvitationsTable.tsx
- src/pages/panel/workspace-settings-users/WorkspaceSettingsUsersTable.tsx
- src/shared/cloud-avatar/CloudAvatar.tsx
- src/shared/constants/panelUI.ts
- src/shared/layouts/panel-layout/table-view-page/TablePagination.tsx
- src/shared/layouts/panel-layout/table-view-page/TableView.tsx
- src/shared/utils/usePersistState.ts
fix table pagination and createIcon
> [fix] fix table pagination and createIcon

- index.html
- src/core/auth/AuthGuard.tsx
- src/pages/panel/shared/utils/sendInventoryError.ts
reduce noise from trackjs on reload
> [fix] reduce noise from trackjs on reload

- src/shared/fix-query-parser/parser.ts
- src/shared/fix-query-parser/query.test.ts
- src/shared/fix-query-parser/query.ts
- src/shared/fix-query-parser/utils.ts
> fix: handle quotes in fulltext term

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/workspace-settings-billing/BillingEntryRow.tsx
- src/pages/panel/workspace-settings-billing/ChangeProductTier.tsx
- src/pages/panel/workspace-settings-billing/ChangeProductTierModal.tsx
- src/pages/panel/workspace-settings-billing/ChangeProductTierToFreeModal.tsx
- src/pages/panel/workspace-settings-billing/WorkspaceSettingsBillingPage.tsx
- src/pages/panel/workspace-settings-billing/getWorkspaceBilling.query.ts
- src/shared/layouts/panel-layout/DrawerMenu.tsx
- src/shared/types/server/responses/GetWorkspaceBilling.ts
use selected_product_tier for showing product tier in billing page
> [fix] use selected_product_tier for showing product tier in billing page

- src/containers/panel/PanelRoutes.tsx
- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/workspace-settings-accounts/WorkspaceSettingsAccountRow.tsx
- src/pages/panel/workspace-settings-billing/ChangePaymentNoMethodModal.tsx
- src/pages/panel/workspace-settings-billing/ChangeProductTier.tsx
- src/pages/panel/workspace-settings-billing/ChangeProductTierModal.tsx
- src/pages/panel/workspace-settings-billing/ConfirmChangePaymentModal.tsx
- src/shared/absolute-navigate/AbsoluteNavigateProvider.tsx
- src/shared/absolute-navigate/getHrefFromTo.ts
- src/shared/absolute-navigate/index.ts
- src/shared/cloud-avatar/CloudAvatar.tsx
- src/shared/link-button/ExternalLinkLoadingButton.tsx
- src/shared/link-button/InternalLinkButton.tsx
- src/shared/link-button/index.ts
- src/shared/modal/Modal.tsx
- src/shared/types/server-shared/Account.ts
- src/shared/types/server-shared/index.ts
Fix message and links for degraded accounts
AWS:
GCP:
Azure:
> [fix] fix message and links for degraded accounts

- src/AppRouter.tsx
- src/core/auth/RequireAuth.tsx
Do not show login screen when already authenticated
> [fix] do not show login screen when already authenticated

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/inventory/InventoryAdvanceSearchTextField.tsx
- src/pages/panel/inventory/InventoryPage.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormAccount.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormCloudValues.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormDefaultValue.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormFilterRowStringValue.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormKind.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormRegionValues.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormReset.tsx
- src/pages/panel/inventory/inventory-form/InventoryFormSeverity.tsx
- src/shared/fix-query-parser/FixQueryContext.tsx
> [Fix] allow to see all resources

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/workspace-settings-billing/ChangeProductTierModal.tsx
- src/pages/panel/workspace-settings-billing/ChangeProductTierToFreeModal.tsx
- src/pages/panel/workspace-settings-billing/ConfirmChangePaymentModal.tsx
- src/pages/panel/workspace-settings-billing/changeProductTierErrorResponseToMessage.ts
- src/pages/panel/workspace-settings-billing/putWorkspaceBilling.mutation.ts
- src/shared/types/server/requests/PutWorkspaceBilling.ts
- src/shared/types/server/requests/index.ts
Update error message on product tier change
updated messages are in [`src/pages/panel/workspace-settings-billing/changeProductTierErrorResponseToMessage.ts`](https://github.com/someengineering/fixfrontend/pull/272/files#diff-a1a4362b07897b52b83286d76f0db61fbb048e1f8de9a7a1ddbadec317b17801)
> [fix] update error message on product tier change

- src/pages/panel/workspace-settings-billing/WorkspaceSettingsBillingPage.tsx
Wrong trial message shown in billing page
> [hotfix] wrong trial message shown in billing page

- src/shared/posthog/PostHogProvider.tsx
Changed parameter for posthog init configuration to enable surveys.
> Enabled posthog surveys

- src/pages/panel/inventory/utils/inventoryTableRenderCell.tsx
> [hotfix] fix when cloud is null

- src/pages/panel/inventory/InventoryTable.tsx
- src/pages/panel/inventory/utils/InventoryTableKindRenderCell.tsx
Add ellipsis to long text in cells
> [fix] add ellipsis to long text in cells

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/workspace-settings-accounts/WorkspaceSettingsAccountErrorLog.tsx
- src/pages/panel/workspace-settings-accounts/WorkspaceSettingsAccountRow.tsx
- src/pages/panel/workspace-settings-accounts/WorkspaceSettingsAccountsTableItem.tsx
- src/pages/panel/workspace-settings-accounts/getWorkspaceCloudAccountsLogs.query.ts
- src/shared/constants/endPoints.ts
- src/shared/link-button/ExternalLink.tsx
- src/shared/link-button/index.ts
- src/shared/types/server-shared/Account.ts
Add Account collect error log in the account overview
> [feat] Add Account collect error log in the account overview

- src/containers/auth/AuthContainer.tsx
- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
> [fix] fix auth left side descs

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/security/OverallScore.tsx
- src/pages/panel/security/Overview.tsx
- src/pages/panel/shared/queries/getWorkspaceInventoryReportSummary.query.ts
- src/shared/types/server/responses/GetWorkspaceInventoryReportSummary.ts
fix report-summary based on the API changes
> [hotfix] fix report-summary based on the API changes

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/workspace-settings-accounts/WorkspaceSettingsAccountRow.tsx
allow enabling accounts in degraded state
> [fix] allow enabling accounts in degraded state

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/user-settings/UserSettingsFormPassword.tsx
- src/pages/panel/user-settings/patchUsersMe.mutation.ts
- src/shared/types/server/requests/PatchCurrentUser.ts
- src/shared/types/server/requests/PostAuthRegister.ts
- src/shared/types/server/requests/index.ts
> [fix] fix update password error

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/workspace-settings-accounts/WorkspaceSettingsAccountRow.tsx
> hotfix(typo-in-accounts): replace Ago to ago

- src/shared/fix-query-parser/parser.test.ts
- src/shared/fix-query-parser/parser.ts
- src/shared/fix-query-parser/query.ts
> feat: Allow passing an edge term filter

- package.json
- yarn.lock
> [chore] bump posthog version

- src/shared/layouts/panel-layout/PanelHeader.tsx
> [fix] temporary fix for top navbar

- src/shared/fix-query-parser/lexer.ts
- src/shared/fix-query-parser/parser.test.ts
- src/shared/fix-query-parser/parser.ts
- src/shared/fix-query-parser/query.ts
> feat: Allow `iam` edges

- src/shared/fix-query-parser/parser.test.ts
- src/shared/fix-query-parser/parser.ts
> fix: navigation from 0

- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/user-settings/UserSettingsNotification.tsx
- src/shared/types/server/requests/PutNotificationUser.ts
- src/shared/types/server/responses/GetNotificationUser.ts
add marketing field to user notification settings
> [fix] [old-main] add marketing field to user notification settings

- src/pages/panel/dashboard/postWorkspaceInventoryAggregateForDashboard.query.ts
- src/pages/panel/security/OverallScore.tsx
- src/pages/panel/shared/utils/createPieDataFromNonCompliance.ts
- src/shared/types/server/responses/PostWorkspaceInventoryAggregateForDashboard.ts
- yarn.lock
Add id to aggregate (world-map data) and add issues to compliance query
> [fix] add id to aggregate (world-map data) and add issues to compliance query

- src/core/auth/AuthGuard.tsx
- src/core/theme/Theme.tsx
- src/core/theme/ThemeContext.ts
- src/locales/de-DE/messages.po
- src/locales/en-US/messages.po
- src/pages/panel/workspace-settings-alert-settings/WorkspaceSettingsAlertSettingsCheckbox.tsx
- src/pages/panel/workspace-settings-alert-settings/WorkspaceSettingsAlertSettingsPage.tsx
- src/pages/panel/workspace-settings-connected-services/WorkspaceSettingsConnectedServicesPage.tsx
- src/pages/panel/workspace-users-settings/WorkspaceSettingsUserActionRowItem.tsx
- src/shared/layouts/panel-layout/UserButton.tsx
- src/shared/layouts/panel-settings-layout/PanelSettingsContent.tsx
- src/shared/layouts/panel-settings-layout/settingsMenuList.tsx
- src/shared/layouts/panel-settings-layout/usePermissionCheck.tsx
Hide item from left side menu on lack of permission
> [fix] Hide item from left side menu on lack of permission
